### ISSUE TITLE
Micro optimization: take only few major colors

### ISSUE THREAD

**Issue by zyishai** [zyishai/image-retriever#1]
**Problem:** when calculating a correlogram, we should calculate specific correlogram for each two colors combination and for each distance. In an image, there are possibly 256<sup>3</sup> different color combinations. Even for small images (e.g 160x160) that's too much (25600! options, not including different distances!!).

**Suggested Solution:** take only few major colors of the image, preferably colors that are close to each other (local correlations between colors are more significant than global correlations). This will also allow us to use relatively small distance.

**Comment by Melchek** [comment]
done. commit: 1eef1bb13ad7747bb9b63aae527487756213fb6b

![image](https://user-images.githubusercontent.com/20405566/91354025-bc92df80-e7f4-11ea-9bff-b6d8c7d3e659.png)

major 18 colors:

![image](https://user-images.githubusercontent.com/20405566/91353896-92412200-e7f4-11ea-94c2-342ac2a5b8b9.png)
